"""
Live streaming endpoints backed by LiveSessionManager (in app.state.live_sessions).

Two parallel channels share a single YOLO loop per (camera_id, area_id):

  GET /api/cameras/{id}/live/video?area_id=X
      multipart/x-mixed-replace MJPEG stream of annotated frames at source_fps.
      Bboxes and zone polygon are burned into each frame by LiveSession.

  GET /api/cameras/{id}/live/events?area_id=X
      SSE stream of rule-engine alarm events plus lifecycle messages
      ({"type": "ended"} on EOF, {"type": "error", ...} on crash).

Sharing the session through the manager is what keeps event timestamps aligned
with the user's video — independent YOLO loops would drift apart.
"""
from __future__ import annotations

import asyncio
import json
import logging
import queue

from fastapi import APIRouter, HTTPException, Request
from fastapi.responses import StreamingResponse

from app.config.cameras import DEMO_CAMERAS
from app.db import get_connection

logger = logging.getLogger(__name__)
router = APIRouter(prefix="/api/cameras", tags=["live-stream"])

MJPEG_BOUNDARY = "frame"


def _get_area_config(area_id: str) -> dict:
    conn = get_connection()
    try:
        row = conn.execute("SELECT * FROM areas WHERE area_id = ?", (area_id,)).fetchone()
    finally:
        conn.close()
    if not row:
        raise HTTPException(status_code=404, detail=f"Area {area_id} not found")
    return {
        "camera_id": row["camera_id"],
        "polygon": json.loads(row["polygon"]),
        "entity_type": row["entity_type"],
        "trigger": json.loads(row["trigger"]),
    }


def _resolve_session(request: Request, camera_id: str, area_id: str):
    """Validate inputs, then get-or-create a LiveSession from the manager."""
    demo_cam = next((c for c in DEMO_CAMERAS if c.id == camera_id), None)
    if not demo_cam:
        raise HTTPException(status_code=404, detail=f"Camera {camera_id} not found")

    area_config = _get_area_config(area_id)
    if area_config["camera_id"] != camera_id:
        raise HTTPException(status_code=400, detail="Area does not belong to this camera")

    manager = request.app.state.live_sessions
    if manager.model is None:
        raise HTTPException(status_code=503, detail="Model not loaded")

    return manager.get_or_create(
        camera_id=camera_id,
        area_id=area_id,
        video_path=demo_cam.video_path,
        area_config=area_config,
    )


@router.get("/{camera_id}/live/video")
async def live_video_stream(camera_id: str, area_id: str, request: Request):
    """
    MJPEG stream of annotated frames at source_fps. Browser renders directly via <img>.
    End-of-stream is signaled on the parallel SSE channel; here we just keep emitting
    the frozen "Stream finalizado" frame until the client disconnects.
    """
    session = _resolve_session(request, camera_id, area_id)
    sub = session.subscribe()
    logger.info(f"MJPEG client attached: camera={camera_id}, area={area_id}, sub={sub.sub_id}")

    async def mjpeg_generator():
        try:
            while True:
                if await request.is_disconnected():
                    break
                try:
                    # Block in a worker thread so the asyncio loop stays free.
                    # Short timeout lets us re-check disconnection frequently.
                    payload = await asyncio.to_thread(sub.jpeg_q.get, True, 0.5)
                except queue.Empty:
                    continue
                if payload is None:  # session-ended sentinel
                    break
                header = (
                    f"--{MJPEG_BOUNDARY}\r\n"
                    f"Content-Type: image/jpeg\r\n"
                    f"Content-Length: {len(payload)}\r\n\r\n"
                ).encode("ascii")
                yield header + payload + b"\r\n"
        finally:
            session.unsubscribe(sub)
            logger.info(f"MJPEG client detached: camera={camera_id}, area={area_id}, sub={sub.sub_id}")

    return StreamingResponse(
        mjpeg_generator(),
        media_type=f"multipart/x-mixed-replace; boundary={MJPEG_BOUNDARY}",
        headers={
            "Cache-Control": "no-cache, private",
            "Pragma": "no-cache",
            "X-Accel-Buffering": "no",
        },
    )


@router.get("/{camera_id}/live/events")
async def live_events_stream(camera_id: str, area_id: str, request: Request):
    """
    SSE stream of rule-engine events generated by the same LiveSession that
    feeds the /live/video MJPEG endpoint.

    Message types emitted:
      {"type": "event",  ...event_fields}        # alarm fired
      {"type": "ended"}                          # source video reached EOF
      {"type": "error", "message": str}          # session crashed
    """
    session = _resolve_session(request, camera_id, area_id)
    sub = session.subscribe()
    logger.info(f"SSE events client attached: camera={camera_id}, area={area_id}, sub={sub.sub_id}")

    async def event_generator():
        try:
            while True:
                if await request.is_disconnected():
                    break
                try:
                    msg = await asyncio.to_thread(sub.event_q.get, True, 0.5)
                except queue.Empty:
                    continue
                if msg is None:  # session-ended sentinel
                    break
                yield f"data: {json.dumps(msg)}\n\n"
        finally:
            session.unsubscribe(sub)
            logger.info(f"SSE events client detached: camera={camera_id}, area={area_id}, sub={sub.sub_id}")

    return StreamingResponse(
        event_generator(),
        media_type="text/event-stream",
        headers={
            "Cache-Control": "no-cache",
            "Connection": "keep-alive",
            "X-Accel-Buffering": "no",
        },
    )


@router.delete("/{camera_id}/live/session")
async def kill_live_session(camera_id: str, area_id: str, request: Request):
    """
    Force-stop the LiveSession for (camera_id, area_id): kills the daemon thread,
    detaches all subscribers, and releases the per-session YOLO model so VRAM/RAM
    is reclaimed. Idempotent — returns {"stopped": false} when no session exists.

    Deliberately skips the area_config DB lookup that GET endpoints do — kill
    must work even if the area row was deleted. Only validates the camera id.

    Synchronous on purpose: the manager joins the loop thread with a 5s bound,
    so the operator gets a definitive "stopped" confirmation in the response.
    """
    demo_cam = next((c for c in DEMO_CAMERAS if c.id == camera_id), None)
    if not demo_cam:
        raise HTTPException(status_code=404, detail=f"Camera {camera_id} not found")
    manager = request.app.state.live_sessions
    stopped = manager.kill_session(camera_id, area_id)
    logger.info(
        f"DELETE /live/session: camera={camera_id}, area={area_id}, stopped={stopped}"
    )
    return {"stopped": stopped}
